### ISSUE TITLE
fail to connect

### ISSUE THREAD

**Issue by Idealist226** [mborgerson/gdbstub#9]
I'm writing my own little OS to run on a real machine and I'm looking to debug it via the serial port. But after I call `gdb_sys_init()` function in kernel file and compile `gdbstub.h` and `gdb_stub_x86_int.nasm` with my OS kernel,  I was unable to connect to the target machine when I ran gdb on another debugger and entered the command `target remote /dev/ttyS0`.  

I can confirm that the serial ports of the two devices can communicate normally. I see that the `gdb_x86_hook_idt()` function called in the `gdb_sys_init()` uses local variables, which seems to have no practical effect, so I tried to call the `gdb_x86_init_idt()` function in `gdb_sys_init()`, but it still doesn't work.

The makefile statements associated with gdbstub are as follows:
> ASMKFLAGS_gdbstub	= -I gdbstub/ -f elf  

>OBJS = os/kernel/kernel.o os/kernel/start.o os/kernel/main.o os/kernel/clock.o\
>&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp; ...
>&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp; os/gdbstub/gdbstub_x86_int.o

>os/gdbstub/gdbstub_x86_int.o: os/gdbstub/gdbstub_x86_int.nasm
>&ensp;&ensp;&ensp;&ensp;&ensp; $(ASM) $(ASMKFLAGS_gdbstub) -o $@ $<

**Comment by mborgerson** [comment]
This all depends on your code, and without seeing it there are only general suggestions I can make:

* Make sure your serial port is working correctly with the functions provided in the stub. Maybe you are using a different port than the stub code expects. You can change the stub to use whatever existing serial functions you have, too.
* `gdb_x86_init_idt` will replace your IDT, which you might not want if you've already set up interrupt handlers in your kernel
* Make sure you're calling `gdb_sys_init`, as demonstrated in gdbstub.c.
* > uses local variables, which seems to have no practical effect
  * The local variables in `gdb_x86_hook_idt` are used to find the location of the current IDT and update it.
* You can use QEMU to more easily debug issues like this. QEMU can provide its own GDB stub that you can connect to, which can help you debug why your debug handling may not be working correctly.

I'll close the issue for now because it doesn't point to an issue with the stub specifically. If you do discover some specific issue, feel free to file again. Good luck!
